-- Final P3 runtime review closure. These definitions replace the live P3 authority
-- functions in place; they do not introduce a parallel runtime path.

-- Keep the service/database secret vocabulary aligned while allowing the canonical
-- structured authorization provenance object generated by runtime control.
CREATE OR REPLACE FUNCTION runtime.jsonb_contains_secret(node jsonb)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE
  k text;
  v jsonb;
  scalar text;
  normalized_key text;
  basic_token text;
  basic_decoded text;
BEGIN
  IF node IS NULL THEN RETURN false; END IF;
  CASE jsonb_typeof(node)
    WHEN 'object' THEN
      FOR k, v IN SELECT key, value FROM jsonb_each(node) LOOP
        normalized_key := lower(regexp_replace(k, '([a-z0-9])([A-Z])', '\1_\2', 'g'));
        IF normalized_key ~ '(^|[_-])(cookie|secret|password|credential)([_-]|$)'
           OR normalized_key ~ '(^|[_-])(proxy[-_]authorization|authorization[-_]header|http[-_]authorization|set[-_]cookie|x[-_]api[-_]key|api[-_]key|access[-_]token|bearer[-_]token)([_-]|$)'
           OR (normalized_key = 'authorization' AND jsonb_typeof(v) = 'string')
           OR runtime.jsonb_contains_secret(v) THEN
          RETURN true;
        END IF;
      END LOOP;
    WHEN 'array' THEN
      FOR v IN SELECT value FROM jsonb_array_elements(node) LOOP
        IF runtime.jsonb_contains_secret(v) THEN RETURN true; END IF;
      END LOOP;
    WHEN 'string' THEN
      scalar := node #>> '{}';
      IF scalar ~* '^\s*bearer\s+[A-Za-z0-9._~+/=-]{8,}\s*$' THEN
        RETURN true;
      END IF;
      IF scalar ~* '^\s*basic\s+[A-Za-z0-9+/]+={0,2}\s*$' THEN
        basic_token := regexp_replace(scalar, '^\s*[Bb][Aa][Ss][Ii][Cc]\s+', '');
        basic_token := regexp_replace(basic_token, '\s+$', '');
        BEGIN
          basic_decoded := convert_from(decode(basic_token, 'base64'), 'UTF8');
          IF position(':' IN basic_decoded) > 0 THEN RETURN true; END IF;
        EXCEPTION WHEN OTHERS THEN
          NULL;
        END;
      END IF;
    ELSE
      NULL;
  END CASE;
  RETURN false;
END $$;

ALTER TABLE runtime.model_routes
  DROP CONSTRAINT IF EXISTS model_routes_policy_object_check,
  ADD CONSTRAINT model_routes_policy_object_check
    CHECK (jsonb_typeof(route_policy) = 'object');

CREATE OR REPLACE FUNCTION runtime.normalize_route_policy() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  m runtime.model_manifests%ROWTYPE;
  authority record;
BEGIN
  IF jsonb_typeof(COALESCE(NEW.route_policy, '{}'::jsonb)) <> 'object' THEN
    RAISE EXCEPTION 'route policy must be a JSON object' USING ERRCODE='23514';
  END IF;
  IF runtime.jsonb_contains_secret(COALESCE(NEW.route_policy, '{}'::jsonb)) THEN
    RAISE EXCEPTION 'route policy must not contain secret or credential material' USING ERRCODE='23514';
  END IF;
  SELECT entity_type,identity_status INTO authority
    FROM core.entities
   WHERE world_id=NEW.world_id AND entity_id=NEW.created_by;
  IF authority.entity_type IS DISTINCT FROM 'SYSTEM'
     OR authority.identity_status IS DISTINCT FROM 'ACTIVE' THEN
    RAISE EXCEPTION 'runtime model route requires ACTIVE SYSTEM authorization' USING ERRCODE='23514';
  END IF;
  SELECT * INTO m FROM runtime.model_manifests
   WHERE world_id=NEW.world_id AND manifest_id=NEW.manifest_id;
  IF m.manifest_id IS NULL THEN
    RAISE EXCEPTION 'route manifest is not available for policy provenance' USING ERRCODE='23514';
  END IF;
  NEW.route_policy := NEW.route_policy || jsonb_build_object(
    'authorization', jsonb_build_object(
      'kind', 'SYSTEM_RUNTIME_CONTROL',
      'policy_version', 'nh.v3.0:p3-runtime-route-policy',
      'authorized_by', NEW.created_by,
      'provenance_basis', 'AUTHORITATIVE_PUBLISH'
    ),
    'provider_scope', jsonb_build_object(
      'descriptor_id', m.gateway_descriptor_id,
      'connector_id', m.gateway_connector_id,
      'provider_protocol', m.provider_protocol,
      'billing_mode', m.billing_mode
    ),
    'data_scope', jsonb_build_object('m03_context', 'DEFERRED_BY_OWNER'),
    'required_capabilities', jsonb_build_array('MODEL_INFERENCE'),
    'fallback', jsonb_build_object('enabled', false)
  );
  RETURN NEW;
END $$;

-- Goal snapshots deduplicate canonical UUID values, allow only the machine-schema
-- pair {goal_id,version}, and compare version text without casting caller input to
-- bigint so oversized decimal strings fail validation instead of surfacing SQL 22003.
CREATE OR REPLACE FUNCTION runtime.populate_checkpoint_authority() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  current_route uuid;
  route_manifest uuid;
  ref jsonb;
  g record;
  version_text text;
  checkpoint_goal_ref_text text;
BEGIN
  IF jsonb_typeof(COALESCE(NEW.pending_actions,'[]'::jsonb)) <> 'array' THEN
    RAISE EXCEPTION 'checkpoint pending_actions must be an array' USING ERRCODE='23514';
  END IF;
  IF NEW.goal_refs IS NULL OR NEW.goal_refs = '[]'::jsonb THEN
    SELECT COALESCE(jsonb_agg(jsonb_build_object('goal_id',goal_id,'version',version) ORDER BY created_at,goal_id),'[]'::jsonb)
      INTO NEW.goal_refs
      FROM runtime.goals
     WHERE world_id=NEW.world_id AND subject_id=NEW.activity_subject_id
       AND status NOT IN ('COMPLETED','ABANDONED','FAILED');
  ELSE
    IF jsonb_typeof(NEW.goal_refs) <> 'array' THEN
      RAISE EXCEPTION 'checkpoint goal_refs must be an array' USING ERRCODE='23514';
    END IF;
    FOR ref IN SELECT value FROM jsonb_array_elements(NEW.goal_refs) LOOP
      IF jsonb_typeof(ref) <> 'object'
         OR NOT (ref ? 'goal_id' AND ref ? 'version')
         OR ref->'goal_id' = 'null'::jsonb
         OR ref->'version' = 'null'::jsonb
         OR (SELECT count(*) FROM jsonb_object_keys(ref)) <> 2 THEN
        RAISE EXCEPTION 'checkpoint goal reference must contain only non-null goal_id and version' USING ERRCODE='23514';
      END IF;
      checkpoint_goal_ref_text := ref->>'goal_id';
      version_text := ref->>'version';
      IF checkpoint_goal_ref_text IS NULL
         OR checkpoint_goal_ref_text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
         OR version_text IS NULL
         OR version_text !~ '^[1-9][0-9]*$' THEN
        RAISE EXCEPTION 'checkpoint goal reference has invalid goal_id or version' USING ERRCODE='23514';
      END IF;
      SELECT goal_id,version INTO g
        FROM runtime.goals
       WHERE world_id=NEW.world_id AND subject_id=NEW.activity_subject_id
         AND goal_id=checkpoint_goal_ref_text::uuid;
      IF g.goal_id IS NULL OR g.version::text <> version_text THEN
        RAISE EXCEPTION 'checkpoint goal reference is not the current authoritative version' USING ERRCODE='23514';
      END IF;
    END LOOP;
    IF (SELECT count(*) FROM jsonb_array_elements(NEW.goal_refs)) <>
       (SELECT count(DISTINCT (value->>'goal_id')::uuid) FROM jsonb_array_elements(NEW.goal_refs)) THEN
      RAISE EXCEPTION 'checkpoint goal_refs must not contain duplicates' USING ERRCODE='23514';
    END IF;
  END IF;

  SELECT current_route_id INTO current_route
    FROM runtime.agent_profiles
   WHERE world_id=NEW.world_id AND agent_entity_id=NEW.activity_subject_id;
  IF current_route IS NULL THEN
    IF jsonb_array_length(NEW.pending_actions) <> 0 THEN
      RAISE EXCEPTION 'checkpoint with pending actions requires a current model route' USING ERRCODE='23514';
    END IF;
    NEW.route_id := NULL;
    NEW.manifest_id := NULL;
    NEW.recovery_authority_status := 'AUTHORITATIVE_PRE_ROUTE';
    RETURN NEW;
  END IF;

  SELECT manifest_id INTO route_manifest
    FROM runtime.model_routes
   WHERE world_id=NEW.world_id AND agent_entity_id=NEW.activity_subject_id AND route_id=current_route;
  IF route_manifest IS NULL THEN
    RAISE EXCEPTION 'checkpoint current route is not authoritative for subject' USING ERRCODE='23514';
  END IF;
  IF NEW.route_id IS NOT NULL AND NEW.route_id <> current_route THEN
    RAISE EXCEPTION 'checkpoint route reference is stale' USING ERRCODE='23514';
  END IF;
  IF NEW.manifest_id IS NOT NULL AND NEW.manifest_id <> route_manifest THEN
    RAISE EXCEPTION 'checkpoint manifest reference does not match route' USING ERRCODE='23514';
  END IF;
  NEW.route_id := current_route;
  NEW.manifest_id := route_manifest;
  NEW.recovery_authority_status := 'AUTHORITATIVE';
  RETURN NEW;
END $$;

-- Same-epoch lease changes are only live-lease heartbeats or a one-way release.
-- Released/expired fencing tokens can never be revived without the next epoch.
CREATE OR REPLACE FUNCTION runtime.guard_runtime_lease_takeover() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.lease_epoch < OLD.lease_epoch THEN
    RAISE EXCEPTION 'runtime lease epoch cannot move backwards' USING ERRCODE='23514';
  END IF;

  IF NEW.lease_epoch = OLD.lease_epoch THEN
    IF NEW.worker_id IS DISTINCT FROM OLD.worker_id
       OR NEW.acquired_at IS DISTINCT FROM OLD.acquired_at THEN
      RAISE EXCEPTION 'same-epoch runtime lease ownership is immutable' USING ERRCODE='23514';
    END IF;

    IF OLD.released_at IS NOT NULL THEN
      IF NEW.released_at IS DISTINCT FROM OLD.released_at
         OR NEW.heartbeat_at IS DISTINCT FROM OLD.heartbeat_at
         OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
        RAISE EXCEPTION 'released runtime lease cannot be revived or renewed at the same epoch' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END IF;

    IF NEW.released_at IS NOT NULL THEN
      IF NEW.heartbeat_at IS DISTINCT FROM OLD.heartbeat_at
         OR NEW.expires_at IS DISTINCT FROM OLD.expires_at THEN
        RAISE EXCEPTION 'runtime lease release cannot also renew the same epoch' USING ERRCODE='23514';
      END IF;
      RETURN NEW;
    END IF;

    IF OLD.expires_at <= now() THEN
      RAISE EXCEPTION 'expired runtime lease requires a new epoch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW.lease_epoch <> OLD.lease_epoch + 1 THEN
    RAISE EXCEPTION 'runtime lease takeover must advance exactly one epoch' USING ERRCODE='23514';
  END IF;
  IF OLD.released_at IS NULL AND OLD.expires_at > now() THEN
    RAISE EXCEPTION 'runtime lease is still active according to database clock' USING ERRCODE='23514';
  END IF;
  IF NEW.released_at IS NOT NULL THEN
    RAISE EXCEPTION 'new runtime lease epoch must begin active' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END $$;

-- Wake evidence is only valid after the database-authoritative due time. MISSED
-- additionally requires the canonical SKIP policy and an actually elapsed latest-run
-- bound. BLOCKED evidence must correspond to a database-verifiable runtime condition;
-- economic failures are reflected into runtime restriction flags by the scheduler.
CREATE OR REPLACE FUNCTION runtime.validate_wake_execution_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  schedule record;
  authority record;
  life record;
  ident text;
BEGIN
  SELECT action_kind,status,subject_id,due_at,latest_run_at,missed_policy INTO schedule
    FROM runtime.scheduled_actions
   WHERE world_id=NEW.world_id AND scheduled_action_id=NEW.scheduled_action_id
   FOR UPDATE;
  IF schedule.action_kind IS DISTINCT FROM 'WAKE'
     OR schedule.status IS DISTINCT FROM 'SCHEDULED'
     OR schedule.subject_id IS DISTINCT FROM NEW.subject_id THEN
    RAISE EXCEPTION 'wake execution evidence requires the matching SCHEDULED WAKE action' USING ERRCODE='23514';
  END IF;
  IF schedule.due_at > now() THEN
    RAISE EXCEPTION 'wake execution evidence cannot precede the authoritative due time' USING ERRCODE='23514';
  END IF;
  IF NEW.outcome='MISSED' AND (
       schedule.missed_policy IS DISTINCT FROM 'SKIP'
       OR schedule.latest_run_at IS NULL
       OR schedule.latest_run_at >= now()
     ) THEN
    RAISE EXCEPTION 'missed wake evidence requires an elapsed SKIP latest-run window' USING ERRCODE='23514';
  END IF;

  SELECT entity_type,identity_status INTO authority
    FROM core.entities WHERE world_id=NEW.world_id AND entity_id=NEW.created_by;
  IF authority.entity_type IS DISTINCT FROM 'SYSTEM' OR authority.identity_status IS DISTINCT FROM 'ACTIVE' THEN
    RAISE EXCEPTION 'wake execution evidence requires ACTIVE SYSTEM authority' USING ERRCODE='23514';
  END IF;

  SELECT life_status,state_version,model_status,restriction_flags INTO life
    FROM runtime.lifecycle_states
   WHERE world_id=NEW.world_id AND activity_subject_id=NEW.subject_id;
  IF life.state_version IS NULL THEN
    RAISE EXCEPTION 'wake execution evidence requires runtime lifecycle state' USING ERRCODE='23514';
  END IF;

  IF NEW.outcome='COMPLETED' THEN
    IF NEW.billing_date IS DISTINCT FROM (now() AT TIME ZONE 'UTC')::date
       OR life.life_status IS DISTINCT FROM 'ACTIVE'
       OR life.state_version IS DISTINCT FROM NEW.lifecycle_state_version THEN
      RAISE EXCEPTION 'completed wake evidence requires current-UTC activated lifecycle evidence' USING ERRCODE='23514';
    END IF;
  ELSIF NEW.outcome='BLOCKED' THEN
    IF NEW.lifecycle_state_version IS NULL
       OR life.state_version IS DISTINCT FROM NEW.lifecycle_state_version THEN
      RAISE EXCEPTION 'blocked wake evidence requires the current lifecycle version' USING ERRCODE='23514';
    END IF;
    SELECT identity_status INTO ident
      FROM core.entities WHERE world_id=NEW.world_id AND entity_id=NEW.subject_id;
    CASE NEW.blocked_reason
      WHEN 'M03_CONTEXT_UNAVAILABLE' THEN
        IF NOT ('M03_CONTEXT_UNAVAILABLE'=ANY(COALESCE(life.restriction_flags,'{}'::text[]))) THEN
          RAISE EXCEPTION 'blocked wake M03 evidence does not match runtime restrictions' USING ERRCODE='23514';
        END IF;
      WHEN 'RUNTIME_RESTRICTED' THEN
        IF NOT (COALESCE(life.restriction_flags,'{}'::text[]) && ARRAY['OWNER_PAUSE','NO_BUDGET','QUARANTINE','WORLD_SUSPENSION']::text[]) THEN
          RAISE EXCEPTION 'blocked wake restriction evidence does not match runtime restrictions' USING ERRCODE='23514';
        END IF;
      WHEN 'MODEL_ROUTE_UNAVAILABLE' THEN
        IF life.model_status='AVAILABLE'
           AND NOT ('NO_MODEL_ROUTE'=ANY(COALESCE(life.restriction_flags,'{}'::text[]))) THEN
          RAISE EXCEPTION 'blocked wake model evidence does not match runtime state' USING ERRCODE='23514';
        END IF;
      WHEN 'IDENTITY_NOT_ACTIVE' THEN
        IF ident='ACTIVE' THEN
          RAISE EXCEPTION 'blocked wake identity evidence does not match M01 identity' USING ERRCODE='23514';
        END IF;
      WHEN 'DAILY_FEE_UNFUNDED' THEN
        IF NOT ('DAILY_FEE_UNFUNDED'=ANY(COALESCE(life.restriction_flags,'{}'::text[]))) THEN
          RAISE EXCEPTION 'blocked wake fee evidence does not match runtime restrictions' USING ERRCODE='23514';
        END IF;
      WHEN 'FIRST_ACTIVATION_MINIMUM_UNFUNDED', 'NO_AVAILABLE_ENERGY' THEN
        IF NOT ('NO_ACTIVITY_ENERGY'=ANY(COALESCE(life.restriction_flags,'{}'::text[]))) THEN
          RAISE EXCEPTION 'blocked wake energy evidence does not match runtime restrictions' USING ERRCODE='23514';
        END IF;
      ELSE
        RAISE EXCEPTION 'unsupported blocked wake evidence reason' USING ERRCODE='23514';
    END CASE;
  END IF;
  RETURN NEW;
END $$;
