-- PostgreSQL truncates autogenerated identifier names to 63 bytes. The legacy
-- connector endpoint uniqueness constraint therefore exists under the truncated
-- name below; remove it so the partial enabled-only index installed by 014 is the
-- sole endpoint uniqueness authority for versioned credential rotation.
ALTER TABLE gateway.connector_configs
  DROP CONSTRAINT IF EXISTS connector_configs_world_id_descriptor_id_connector_kind_bas_key,
  DROP CONSTRAINT IF EXISTS connector_configs_world_id_descriptor_id_connector_kind_base_url_key;
