import test from 'node:test';
import assert from 'node:assert/strict';
import { createPool, withTransaction } from '../../src/db.js';
import { createEntity, runCommand } from '../../src/services/core.js';
import { chargeDailyActivityFee, firstActivation, getWallet, mint, reserve, transfer } from '../../src/services/economy.js';

const pool=createPool(); const world='test-world'; let system;
async function reset(){await pool.query('TRUNCATE core.consumer_receipts, core.outbox, core.life_events, economy.activity_fees, economy.activity_subjects, economy.reservations, economy.postings, economy.journals, economy.wallets, core.actions, core.capability_grants, core.entities RESTART IDENTITY CASCADE');system=await withTransaction(pool,(c)=>createEntity(c,{worldId:world,entityType:'SYSTEM',displayId:'system',name:'System'}));}
async function entity(type,name){return withTransaction(pool,(c)=>createEntity(c,{worldId:world,entityType:type,displayId:`${name}-${crypto.randomUUID()}`,name,createdBy:system.entity_id},{actorEntityId:system.entity_id}));}
async function mintTo(target,amount,basis=crypto.randomUUID()){return runCommand(pool,{worldId:world,actorEntityId:system.entity_id,actionType:'economy.mint',idempotencyKey:`mint-action-${basis}`,payload:{target:target.entity_id,amount,basis}},(c,ctx)=>mint(c,{worldId:world,targetEntityId:target.entity_id,amountMicroE:amount,basisKey:basis,actorEntityId:system.entity_id,actionId:ctx.actionId}));}
test.beforeEach(reset); test.after(async()=>pool.end());

test('same payment command replayed 1000 times has one net effect',async()=>{const a=await entity('AGENT','a');const command={worldId:world,actorEntityId:system.entity_id,actionType:'economy.mint',idempotencyKey:'same-payment',payload:{target:a.entity_id,amount:'100000000',basis:'basis-1'}};for(let i=0;i<1000;i++)await runCommand(pool,command,(c,ctx)=>mint(c,{worldId:world,targetEntityId:a.entity_id,amountMicroE:'100000000',basisKey:'basis-1',actorEntityId:system.entity_id,actionId:ctx.actionId}));const wallet=await withTransaction(pool,(c)=>getWallet(c,world,a.entity_id));assert.equal(wallet.posted_balance_micro_e,'100000000');assert.equal((await pool.query("SELECT count(*)::int n FROM economy.journals WHERE journal_type='MINT'")).rows[0].n,1);});

test('concurrent spends never exceed posted available balance',async()=>{const source=await entity('AGENT','source'),dest=await entity('AGENT','dest');await mintTo(source,'10000000','concurrency-seed');const attempts=Array.from({length:20},(_,i)=>runCommand(pool,{worldId:world,actorEntityId:source.entity_id,actionType:'economy.transfer',idempotencyKey:`spend-${i}`,payload:{i}},(c,ctx)=>transfer(c,{worldId:world,fromEntityId:source.entity_id,toEntityId:dest.entity_id,amountMicroE:'1000000',businessKey:`spend-${i}`,actorEntityId:source.entity_id,actionId:ctx.actionId})));const settled=await Promise.allSettled(attempts);assert.equal(settled.filter(x=>x.status==='fulfilled').length,10);const sw=await withTransaction(pool,(c)=>getWallet(c,world,source.entity_id)),dw=await withTransaction(pool,(c)=>getWallet(c,world,dest.entity_id));assert.equal(sw.posted_balance_micro_e,'0');assert.equal(dw.posted_balance_micro_e,'10000000');});

test('99.999999 / 100 / 101 E activation boundaries are exact',async()=>{const low=await entity('AGENT','low'),exact=await entity('AGENT','exact'),high=await entity('AGENT','high');await mintTo(low,'99999999','low');await mintTo(exact,'100000000','exact');await mintTo(high,'101000000','high');await assert.rejects(()=>runCommand(pool,{worldId:world,actorEntityId:low.entity_id,actionType:'economy.first_activation',idempotencyKey:'low-act',payload:{}},(c,ctx)=>firstActivation(c,{worldId:world,entityId:low.entity_id,billingDate:'2026-09-16',actorEntityId:low.entity_id,actionId:ctx.actionId})),e=>e.code==='FIRST_ACTIVATION_MINIMUM_UNFUNDED');const er=await runCommand(pool,{worldId:world,actorEntityId:exact.entity_id,actionType:'economy.first_activation',idempotencyKey:'exact-act',payload:{}},(c,ctx)=>firstActivation(c,{worldId:world,entityId:exact.entity_id,billingDate:'2026-09-16',actorEntityId:exact.entity_id,actionId:ctx.actionId}));const hr=await runCommand(pool,{worldId:world,actorEntityId:high.entity_id,actionType:'economy.first_activation',idempotencyKey:'high-act',payload:{}},(c,ctx)=>firstActivation(c,{worldId:world,entityId:high.entity_id,billingDate:'2026-09-16',actorEntityId:high.entity_id,actionId:ctx.actionId}));assert.equal(er.result.wallet.available_micro_e,'99000000');assert.equal(er.result.eligibility.canSeekTasks,false);assert.equal(hr.result.wallet.available_micro_e,'100000000');assert.equal(hr.result.eligibility.canSeekTasks,true);});

test('concurrent first-activation attempts cannot create two first activations',async()=>{const a=await entity('AGENT','first-race');await mintTo(a,'110000000','first-race-seed');const calls=[['first-a','2026-09-16'],['first-b','2026-09-17']].map(([key,date])=>runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'economy.first_activation',idempotencyKey:key,payload:{date}},(c,ctx)=>firstActivation(c,{worldId:world,entityId:a.entity_id,billingDate:date,actorEntityId:a.entity_id,actionId:ctx.actionId})));const settled=await Promise.allSettled(calls);assert.equal(settled.filter(x=>x.status==='fulfilled').length,1);assert.equal(settled.filter(x=>x.status==='rejected'&&x.reason.code==='ALREADY_ACTIVATED').length,1);assert.equal((await pool.query('SELECT count(*)::int n FROM economy.activity_fees WHERE activity_subject_id=$1',[a.entity_id])).rows[0].n,1);});

test('same UTC day fee charged once under concurrent commands',async()=>{const a=await entity('AGENT','fee');await mintTo(a,'110000000','fee-seed');await runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'economy.first_activation',idempotencyKey:'activate-day-1',payload:{}},(c,ctx)=>firstActivation(c,{worldId:world,entityId:a.entity_id,billingDate:'2026-09-15',actorEntityId:a.entity_id,actionId:ctx.actionId}));const attempts=Array.from({length:25},(_,i)=>runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'economy.daily_fee',idempotencyKey:`fee-${i}`,payload:{date:'2026-09-16'}},(c,ctx)=>chargeDailyActivityFee(c,{worldId:world,entityId:a.entity_id,billingDate:'2026-09-16',actorEntityId:a.entity_id,actionId:ctx.actionId})));const settled=await Promise.allSettled(attempts);assert.equal(settled.filter(x=>x.status==='fulfilled').length,25);const wallet=await withTransaction(pool,(c)=>getWallet(c,world,a.entity_id));assert.equal(wallet.posted_balance_micro_e,'108000000');assert.equal((await pool.query('SELECT count(*)::int n FROM economy.activity_fees WHERE activity_subject_id=$1',[a.entity_id])).rows[0].n,2);});

test('active reservation is excluded from available balance',async()=>{const a=await entity('AGENT','reserve');await mintTo(a,'100000000','reserve-seed');await runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'economy.reserve',idempotencyKey:'reserve-action',payload:{}},(c,ctx)=>reserve(c,{worldId:world,entityId:a.entity_id,amountMicroE:'20000000',businessKey:'model-budget',actorEntityId:a.entity_id,actionId:ctx.actionId}));const wallet=await withTransaction(pool,(c)=>getWallet(c,world,a.entity_id));assert.equal(wallet.posted_balance_micro_e,'100000000');assert.equal(wallet.reserved_micro_e,'20000000');assert.equal(wallet.available_micro_e,'80000000');});

test('payload cannot spoof the server-bound action actor',async()=>{const a=await entity('AGENT','actor-a'),b=await entity('AGENT','actor-b');const result=await runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'core.actor_binding_probe',idempotencyKey:'actor-bind',payload:{actorEntityId:b.entity_id}},async(_c,ctx)=>({boundActor:ctx.actor.entity_id}));assert.equal(result.result.boundActor,a.entity_id);const row=(await pool.query('SELECT actor_entity_id FROM core.actions WHERE action_id=$1',[result.actionId])).rows[0];assert.equal(row.actor_entity_id,a.entity_id);});

test('same idempotency key with different payload is rejected',async()=>{const a=await entity('AGENT','idempotency');await mintTo(a,'10000000','idempotency-seed');await runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'noop',idempotencyKey:'collision',payload:{x:1}},async()=>({ok:true}));await assert.rejects(()=>runCommand(pool,{worldId:world,actorEntityId:a.entity_id,actionType:'noop',idempotencyKey:'collision',payload:{x:2}},async()=>({ok:true})),e=>e.code==='IDEMPOTENCY_CONFLICT');});
